---
galaxy_info:
  author: Pierre Buyle & Pierre Paul Lefebvre
  description: Manage a simple exim4 configuration
  company: Pheromone
  license: license (GPLv2, CC-BY, etc)
  min_ansible_version: 1.2
  platforms:
  - name: Ubuntu
    versions:
    - all
  - name: Debian
    versions:
    - all
  categories:
  - networking
  - packaging
dependencies: []
