---
# defaults file for exim4
exim4_dc_eximconfig_configtype: local
exim4_dc_other_hostnames: "{{ ansible_hostname }}"
exim4_dc_local_interfaces: '127.0.0.1 ; ::1'
exim4_dc_readhost: ''
exim4_dc_relay_domains: ''
exim4_dc_minimaldns: 'false'
exim4_dc_relay_nets: ''
exim4_dc_smarthost: ''
exim4_CFILEMODE: '644'
exim4_dc_use_split_config: 'false'
exim4_dc_hide_mailname: ''
exim4_dc_mailname_in_oh: 'true'
exim4_dc_localdelivery: 'mail_spool'

# Extract selector from the key file name by default
exim4_dkim_selector: ${extract{-1}{.}{DKIM_PRIVATE_KEY{{'}}'}}
exim4_dkim_domain: ${lc:${domain:$h_from:{{'}}'}}
exim4_dkim_canon: 'relaxed'
