---
- name: create sentry directories
  file: path=/var/www/sentry/ mode=0755 state=directory

- name: create sentry/docker-compose.yml
  template:
    src: docker-compose.yml.j2
    dest: /var/www/sentry/docker-compose.yml

- name: copy sentry config files
  copy:
    src: '{{ item }}'
    dest: '/var/www/sentry/{{ item }}'
  with_items:
    - config.yml
    - sentry.conf.py
    - Dockerfile

- name: build container
  shell: docker-compose build
  args:
    chdir: /var/www/sentry/

- name: migrate database
  shell: docker-compose run --rm web upgrade --noinput
  args:
    chdir: /var/www/sentry/

- name: start app
  shell: docker-compose up -d
  args:
    chdir: /var/www/sentry/

- name: generate SSL certificate with Let's encrypt certbot
  shell: certbot certonly --cert-name {{ sentry_domain_name }} -n --webroot -w /var/www/letsencrypt/ -m {{ letsencrypt_email }} --agree-tos -d {{ sentry_domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ sentry_domain_name }}/cert.pem

- name: copy sentry nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/sentry.conf
  notify: restart nginx

- name: enable sentry in nginx
  file: src=/etc/nginx/sites-available/sentry.conf dest=/etc/nginx/sites-enabled/sentry.conf state=link
  notify: restart nginx
