---
- name: Create directories for blog
  file:
    state: directory
    path: "{{ item }}"
    mode: 0755
  with_items:
    - /opt/ghost
    - /opt/ghost/ghost
    - /opt/ghost/mysql

- name: Copy docker-compose.yml
  copy:
    src: docker-compose.yml
    dest: /opt/ghost/ghost/docker-compose.yml

- name: Start Ghost Blog
  shell: docker-compose up -d
  args:
    chdir: /opt/ghost/ghost

- name: generate SSL certificate with Let's encrypt certbot
  shell: certbot certonly --cert-name {{ ghost_domain_name }} -n --webroot -w /var/www/letsencrypt/ -m {{ letsencrypt_email }} --agree-tos -d {{ ghost_domain_name }}
  args:
    creates: /etc/letsencrypt/live/{{ ghost_domain_name }}/cert.pem

- name: copy ghost nginx config
  template: src=nginx.conf.j2 dest=/etc/nginx/sites-available/ghost.conf
  notify: restart nginx

- name: enable ghost in nginx
  file: src=/etc/nginx/sites-available/ghost.conf dest=/etc/nginx/sites-enabled/ghost.conf state=link
  notify: restart nginx
