# Generated by Django 2.0.1 on 2018-01-08 00:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

def set_default_recipient(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Notification = apps.get_model('core', 'Notification')
    u = User.objects.first() or User.objects.create(email='placeholder-migrations@dummy.user.no')

    Notification.objects.update(recipient=u)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.RunPython(code=set_default_recipient, reverse_code=migrations.RunPython.noop),
        migrations.AlterField(
          model_name='notification',
          name='recipient',
          field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, related_name='notifications',
                                  to=settings.AUTH_USER_MODEL),
          preserve_default=False,
        ),
    ]
