# Generated by Django 2.0.1 on 2018-01-25 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20180125_0600'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='videofile',
            field=models.FileField(default='', upload_to='videos'),
            preserve_default=False,
        ),
    ]
