# Generated by Django 2.0.1 on 2018-01-25 21:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_video_videofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='hashtags',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos', to='core.Hashtag'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, null=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='products',
            field=models.ManyToManyField(blank=True, null=True, related_name='videos', to='core.Product'),
        ),
    ]
