# Generated by Django 2.0.1 on 2018-01-26 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_auto_20180125_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('cover_photo', models.FileField(upload_to='collection_covers')),
            ],
        ),
        migrations.CreateModel(
            name='EditorialRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('collections', models.ManyToManyField(related_name='_editorialrecommendation_collections_+', to='core.Collection')),
            ],
        ),
        migrations.AlterField(
            model_name='featuredvideo',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_video', to='core.Video'),
        ),
        migrations.AlterField(
            model_name='video',
            name='hashtags',
            field=models.ManyToManyField(blank=True, related_name='videos', to='core.Hashtag'),
        ),
        migrations.AlterField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_videos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='video',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='videos', to='core.Product'),
        ),
        migrations.AddField(
            model_name='editorialrecommendation',
            name='featured_videos',
            field=models.ManyToManyField(related_name='_editorialrecommendation_featured_videos_+', to='core.Video'),
        ),
        migrations.AddField(
            model_name='collection',
            name='videos',
            field=models.ManyToManyField(related_name='_collection_videos_+', to='core.Video'),
        ),
    ]
