# Generated by Django 2.0.1 on 2018-01-26 10:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_auto_20180126_0033'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportVideo',
            fields=[
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Video')),
                ('reason', models.CharField(choices=[('reason1', 'Reason 1'), ('reason2', 'Reason 2'), ('reason3', 'Reason 3')], max_length=20)),
            ],
        ),
    ]
