# Generated by Django 2.0.1 on 2018-01-30 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_auto_20180130_2133'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('like', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Like')),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Video')),
            ],
        ),
        migrations.AddField(
            model_name='video',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='liked_videos', through='core.LikeVideo', to='core.Like'),
        ),
    ]
