# Generated by Django 2.0.1 on 2018-02-02 08:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_reportvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportedVideo',
            fields=[
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='core.Video')),
                ('reviewed', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='reportvideo',
            name='video',
        ),
        migrations.DeleteModel(
            name='ReportVideo',
        ),
    ]
