# Generated by Django 2.0.1 on 2018-02-01 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180130_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='video',
            name='published',
            field=models.DateTimeField(default=None),
        ),
    ]
