# Generated by Django 2.0.1 on 2018-02-04 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20180202_0816'),
        ('core', '0021_auto_20180202_0545'),
    ]

    operations = [
    ]
