# Generated by Django 2.0.1 on 2018-02-07 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20180205_1716'),
        ('core', '0023_auto_20180205_1447'),
    ]

    operations = [
    ]
