# Generated by Django 2.0.1 on 2018-02-15 10:29

from django.db import migrations, models
import django.db.models.deletion

def _remove_stale_comments(apps, schema_editor):
    """
    Removes stale comments from the db. Comments before this point could not have been assigned to a Video, thus are
    meaningless (and must have been a byproduct of earlier development/testing).
    """
    Comment = apps.get_model('core', 'Comment')
    Comment.objects.all().delete()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180208_1559'),
    ]

    operations = [
        migrations.RunPython(code=_remove_stale_comments, reverse_code=migrations.RunPython.noop),

        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='core.Video'),
            preserve_default=False,
        ),
    ]
