# Generated by Django 2.0.1 on 2018-02-15 21:59

from django.db import migrations


def _forward(apps, schema_editor):
    User = apps.get_model('core', 'User')
    User.objects.filter(email='placeholder-migrations@dummy.user.no').update(is_active=False)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_auto_20180208_1559'),
    ]

    operations = [
        migrations.RunPython(code=_forward, reverse_code=migrations.RunPython.noop)
    ]
