# Generated by Django 2.0.1 on 2018-02-17 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_set_placeholder_user_inactive'),
        ('core', '0029_auto_20180217_0021'),
    ]

    operations = [
    ]
