# Generated by Django 2.0.1 on 2018-02-21 03:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_order_product'),
        ('core', '0030_merge_20180217_0032'),
    ]

    operations = [
    ]
