# Generated by Django 2.0.1 on 2018-02-21 03:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_merge_20180221_0332'),
        ('core', '0027_comment_video'),
    ]

    operations = [
    ]
