# Generated by Django 2.0.1 on 2018-02-23 08:36

from django.db import migrations, models
import heartface.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20180221_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=heartface.apps.core.models.get_file_path),
        ),
        migrations.AddField(
            model_name='product',
            name='price',
            field=models.IntegerField(default=0),
        ),
    ]
