# Generated by Django 2.0.1 on 2018-02-23 09:52

from django.db import migrations, models
import heartface.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20180221_0348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='videofile',
            field=models.FileField(upload_to=heartface.apps.core.models.uuid4_title),
        ),
    ]
