# Generated by Django 2.0.1 on 2018-03-05 02:39

from django.db import migrations

def _create_dummy_user(apps, schema_editor):
    User = apps.get_model('core', 'User')
    if not User.objects.filter(email='placeholder-migrations@dummy.user.no').exists():
        User.objects.create(email='placeholder-migrations@dummy.user.no',
                            username='migrations@dummy.user.no', is_active=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_merge_20180221_0348'),
    ]

    operations = [
        migrations.RunPython(code=_create_dummy_user, reverse_code=migrations.RunPython.noop)
    ]
