# Generated by Django 2.0.1 on 2018-03-09 07:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_order_datetime'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='datetime',
            new_name='created',
        ),
    ]
