# Generated by Django 2.0.1 on 2018-03-02 06:53

from django.db import migrations, models
import django.utils.timezone
import heartface.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_auto_20180223_0836'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(default='', upload_to=heartface.apps.core.models.get_file_path),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(default='', upload_to=heartface.apps.core.models.get_file_path),
        ),
    ]
