# Generated by Django 2.0.1 on 2018-03-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_follow'),
    ]

    operations = [
        # migrations.RemoveField(
        #     model_name='user',
        #     name='followers',
        # ),
    ]
