# Generated by Django 2.0.1 on 2018-03-05 02:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion

from heartface.apps.core.models import User

def _set_dummy_reporter(apps, schema_editor):
    User = apps.get_model('core', 'User')
    ReportedVideo = apps.get_model('core', 'ReportedVideo')
    u = User.objects.get(email='placeholder-migrations@dummy.user.no')
    ReportedVideo.objects.filter(reporting_user=None).update(reporting_user=u)


class Migration(migrations.Migration):
  dependencies = [
    ('core', '0033_create_placeholder_user_if_not_exists'),
  ]

  operations = [
    migrations.AddField(
        model_name='reportedvideo',
        name='reporting_user',
        field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE,
                                to=settings.AUTH_USER_MODEL),
        preserve_default=False,
    ),
    migrations.RunPython(code=_set_dummy_reporter, reverse_code=migrations.RunPython.noop),
    migrations.AlterField(
        model_name='reportedvideo',
        name='reporting_user',
        field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        preserve_default=False,
    )
  ]
