# Generated by Django 2.0.1 on 2018-02-28 16:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0033_device'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='notification_id',
            field=models.CharField(default='', max_length=50),
            preserve_default=False,
        ),
    ]
