# Generated by Django 2.0.1 on 2018-03-08 00:14

from django.db import migrations, models
import heartface.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20180302_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='picture',
            field=models.ImageField(upload_to=heartface.apps.core.models.UploadDir('product_images')),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='logo',
            field=models.ImageField(upload_to=heartface.apps.core.models.UploadDir('supplier_logo')),
        ),
    ]
