# Generated by Django 2.0.1 on 2018-03-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_reportedvideo_reporting_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='retailer_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
