# Generated by Django 2.0.1 on 2018-03-19 11:52

from django.conf import settings
from django.db import migrations, models

def _copy_to_through_model(apps, schema_editor):
    User = apps.get_model('core', 'User')
    Follow = apps.get_model('core', 'Follow')

    for u in User.objects.all():
        for follower_id in u.followers.all().values_list('pk', flat=True):
          Follow.objects.create(from_user=u, to_user_id=follower_id)


def _copy_from_through_model(apps, schema_editor):
  User = apps.get_model('core', 'User')
  Follow = apps.get_model('core', 'Follow')

  for u in User.objects.all():
      u.followers.add(*list(Follow.objects.filter(from_user=u).values_list('pk', flat=True)))


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_remove_user_followers'),
    ]

    operations = [
        # migrations.AlterField(
        migrations.RunPython(code=_copy_to_through_model, reverse_code=_copy_from_through_model),
        migrations.AddField(
            model_name='user',
            name='new_followers',
            field=models.ManyToManyField(related_name='following', through='core.Follow', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='user',
            name='followers',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='new_followers',
            new_name='followers'
        )
    ]
