# Generated by Django 2.0.1 on 2018-03-08 00:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_auto_20180308_0014'),
        ('core', '0037_user_phone'),
    ]

    operations = [
    ]
