# Generated by Django 2.0.1 on 2018-03-11 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_auto_20180309_0716'),
        ('core', '0038_merge_20180308_0054'),
    ]

    operations = [
    ]
