# Generated by Django 2.0.1 on 2018-03-20 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0040_remove_user_is_verified'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='full_name',
            field=models.CharField(default='', max_length=60, verbose_name='full name'),
            preserve_default=False,
        ),
    ]
