# Generated by Django 2.0.1 on 2018-03-20 13:47
import django
from django.db import migrations
from django.db import models
from django.db.models import F, Value
from django.db.models.functions import Concat


def set_full_name(apps, schema_editor):
    apps.get_model('core', 'User').objects.all().update(full_name=Concat(F('first_name'), Value(' '), F('last_name')))

def split_name(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for u in User.objects.all():
        u.first_name, u.last_name, *_ = u.full_name.rsplit(maxsplit=1) + ['', '']
        u.save()

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0041_user_full_name'),
    ]

    operations = [
        # We'll need to allow nulls until we back populate these fields when reversing the migrations
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(max_length=30, verbose_name='last name', null=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=30, verbose_name='first name', null=True),
            preserve_default=False,
        ),
        migrations.RunPython(code=set_full_name, reverse_code=split_name),
    ]
