# Generated by Django 2.0.1 on 2018-03-23 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_notification_notification_id'),
        ('core', '0042_auto_20180320_1248'),
    ]

    operations = [
    ]
