# Generated by Django 2.0.1 on 2018-03-23 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20180320_1352'),
        ('core', '0042_auto_20180320_1248'),
    ]

    operations = [
    ]
