# Generated by Django 2.0.1 on 2018-03-23 13:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_auto_20180320_1352'),
        ('core', '0043_merge_20180323_0707'),
    ]

    operations = [
    ]
