# Generated by Django 2.0.1 on 2018-03-23 07:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_merge_20180323_0734'),
        ('core', '0035_user_followers'),
    ]

    operations = [
    ]
