# Generated by Django 2.0.1 on 2018-03-28 01:45

from django.db import migrations, models
import django.db.models.deletion
import heartface.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_merge_20180323_0734'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPicture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to=heartface.apps.core.models.UploadDir('product_images'))),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pictures', to='core.Product')),
            ],
        ),
    ]
