# Generated by Django 2.0.1 on 2018-03-28 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_productpicture'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='picture',
            new_name='primary_picture',
        ),
    ]
