# Generated by Django 2.0.1 on 2018-03-28 02:25

from django.db import migrations, models


def _move_to_supplier_product(apps, schema):
    Product = apps.get_model('core', 'Product')
    SupplierProduct = apps.get_model('core', 'SupplierProduct')

    for p in Product.objects.all():
        SupplierProduct.objects.create(product=p, supplier=p.supplier, price=p.price, link=p.link)

def _move_from_supplier_product(apps, schema):
    Product = apps.get_model('core', 'Product')
    SupplierProduct = apps.get_model('core', 'SupplierProduct')

    # We only have place for info from a single supplier
    for sp in SupplierProduct.objects.all().distinct('product'):
        Product.objects.filter(pk=sp.product.pk).update(link = sp.link, price = sp.price, supplier = sp.supplier)

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_supplierproduct'),
    ]

    operations = [
        # NOTE: nulls should be allowed from here, since when going reverse, this is the point when we'll populate
        # these fields with data
        migrations.AlterField(
            model_name='product',
            name='link',
            field=models.URLField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='supplier',
            field=models.ForeignKey('Supplier', default='', null=True, related_name='products',
                                    on_delete=models.CASCADE)
        ),
        migrations.RunPython(code=_move_to_supplier_product, reverse_code=_move_from_supplier_product)
    ]
