# Generated by Django 2.0.3 on 2018-04-02 05:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_auto_20180328_0426'),
        ('core', '0033_auto_20180223_0952'),
    ]

    operations = [
    ]
