# Generated by Django 2.0.4 on 2018-04-20 02:43

from django.db import migrations

def _link_orders_to_supplier_products(apps, schema_editor):
    Order = apps.get_model('core', 'Order')

    for order in Order.objects.all():
        # We're not using .first() because that could return None and supplier_product will be non-nullable
        order.supplier_product = order.product.supplier_info.all()[0]
        order.size = (order.supplier_product.sizes + [1.0])[0]
        order.save()

def _link_orders_to_products(apps, schema_editor):
    Order = apps.get_model('core', 'Order')

    for order in Order.objects.all():
        # F() objects don't allow joins with updates...
        order.product = order.supplier_product.product
        order.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20180405_0247'),
    ]

    operations = [
        migrations.RunPython(
            code=_link_orders_to_supplier_products,
            reverse_code=_link_orders_to_products
        ),
    ]
