# Generated by Django 2.0.1 on 2018-04-03 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_merge_20180323_1308'),
        ('core', '0053_merge_20180402_0536'),
    ]

    operations = [
    ]
