# Generated by Django 2.0.1 on 2018-04-04 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_merge_20180402_0536'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='title',
            field=models.CharField(default='', max_length=255),
        ),
    ]
