# Generated by Django 2.0.1 on 2018-04-03 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20180403_0653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='player_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
