# Generated by Django 2.0.3 on 2018-04-05 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_auto_20180405_0329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order',
            old_name='supplier_product',
            new_name='product',
        ),
    ]
