# Generated by Django 2.0.1 on 2018-04-05 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20180405_0331'),
        ('core', '0054_products_to_supplier_products'),
    ]

    operations = [
    ]
