# Generated by Django 2.0.4 on 2018-04-10 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_auto_20180403_1311'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='player_id_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='notification_id_uuid',
            field=models.UUIDField(null=True),
        ),
        migrations.AlterField(
            model_name='device',
            name='player_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
