# Generated by Django 2.0.1 on 2018-04-05 13:12

from django.db import migrations
from djstripe.models import Customer

import heartface


def create_customer(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for user in User.objects.filter(djstripe_customers__isnull=True):
        # This is a dirty hack to trick the ORM into accepting the fake User model for a real one
        user._meta.concrete_model = heartface.apps.core.models.User
        user.__class__ = heartface.apps.core.models.User
        Customer.get_or_create(subscriber=user)


def remove_customer(apps, schema_editor):
    # We don't *have to* delete dangling customers at this point
    pass

class Migration(migrations.Migration):
    dependencies = [
        ('core', '0057_merge_20180405_0753'),
        # This is, though undocumented, supposed to work, but it doesn't:
        # ('djstripe', '__latest__')
        ('djstripe', '0020_auto_20180110_0842')
    ]

    operations = [
        migrations.RunPython(code=create_customer, reverse_code=remove_customer),
    ]
