# Generated by Django 2.0.4 on 2018-04-10 04:06
import uuid

from django.db import migrations

def _from_char_to_uuid(apps, schema_editor):
    Notification = apps.get_model('core', 'Notification')

    for n in Notification.objects.all():
        try:
            uid = uuid.UUID(n.notification_id.strip()) if n.notification_id else uuid.uuid4()
            if Notification.objects.filter(notification_id_uuid=uid).exists():
                uid = uuid.uuid4()
        except:
            uid = uuid.uuid4()
        n.notification_id_uuid = uid
        n.save()

    Device = apps.get_model('core', 'Device')

    for n in Device.objects.all():
        try:
            uid = uuid.UUID(n.player_id.strip()) if n.player_id else uuid.uuid4()
            if Device.objects.filter(player_id_uuid=uid).exists():
                uid = uuid.uuid4()
        except:
            uid = uuid.uuid4()
        n.player_id_uuid = uid
        n.save()


def _from_uuid_to_char(apps, schema_editor):
    for type, fname in [('Notification', 'notification_id'), ('Device', 'player_id')]:
        Type = apps.get_model('core', type)

        for o in Type.objects.all():
            setattr(o, fname, getattr(o, '%s_uuid' % fname))
            o.save()

class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_auto_20180410_0405'),
    ]

    operations = [
        migrations.RunPython(code=_from_char_to_uuid, reverse_code=_from_uuid_to_char)
    ]
