# Generated by Django 2.0.4 on 2018-04-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_convert_chars_to_uuid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device',
            name='player_id',
        ),
        migrations.RemoveField(
            model_name='notification',
            name='notification_id',
        ),
    ]
