# Generated by Django 2.0.1 on 2018-04-06 07:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    # TODO: check which stripe version we can use. djangostripe1.0.0 supports 2017-06-20?
    dependencies = [
        # 0011_auto_20170808_0628
        # ('djstripe', '0020_auto_20161229_0041'), #
        # ('djstripe', '__latest__'), # _20180110_0842
        # ('djstripe', '0011_auto_20170808_0628'), # _20180110_0842
        # ('djstripe', '__latest__'), # _20180110_0842
        ('core', '0058_auto_20180405_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='charge',
            field=models.OneToOneField(null=True, blank=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.Charge'),
            preserve_default=False,
        ),
    ]
