# Generated by Django 2.0.4 on 2018-04-10 04:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_auto_20180410_0422'),
    ]

    operations = [
        migrations.RenameField(
            model_name='device',
            old_name='player_id_uuid',
            new_name='player_id',
        ),
        migrations.RenameField(
            model_name='notification',
            old_name='notification_id_uuid',
            new_name='notification_id',
        ),
    ]
