# Generated by Django 2.0.1 on 2018-04-06 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_order_charge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='charge',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.Charge'),
        ),
    ]
