# Generated by Django 2.0.4 on 2018-04-10 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_auto_20180410_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='device',
            name='player_id',
            field=models.UUIDField(unique=True),
        ),
        migrations.AlterField(
            model_name='notification',
            name='notification_id',
            field=models.UUIDField(unique=True),
        ),
    ]
