# Generated by Django 2.0.4 on 2018-04-17 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20180410_0424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'New'), (1, 'Being processed'), (2, 'Ordered'), (3, 'Confirmed')]),
        ),
    ]
