# Generated by Django 2.0.4 on 2018-04-13 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20180410_0424'),
        ('core', '0046_auto_20180327_0110'),
    ]

    operations = [
    ]
