# Generated by Django 2.0.1 on 2018-04-14 12:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_auto_20180410_0424'),
    ]

    operations = [
        migrations.CreateModel(
            name='Trending',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrendingHashtag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('hashtag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Hashtag')),
                ('trending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trending')),
            ],
        ),
        migrations.CreateModel(
            name='TrendingProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField()),
                ('trending', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Trending')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='trending',
            name='hashtags',
            field=models.ManyToManyField(through='core.TrendingHashtag', to='core.Hashtag'),
        ),
        migrations.AddField(
            model_name='trending',
            name='profiles',
            field=models.ManyToManyField(through='core.TrendingProfile', to=settings.AUTH_USER_MODEL),
        ),
    ]
