# Generated by Django 2.0.1 on 2018-04-14 12:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20180414_1203'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trendinghashtag',
            options={'ordering': ('-score',)},
        ),
        migrations.AlterModelOptions(
            name='trendingprofile',
            options={'ordering': ('-score',)},
        ),
    ]
