# Generated by Django 2.0.4 on 2018-04-17 05:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_auto_20180417_0504'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='handled_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
