# Generated by Django 2.0.4 on 2018-04-19 05:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_order_handled_by'),
        ('core', '0062_merge_20180413_1623'),
    ]

    operations = [
    ]
