# Generated by Django 2.0.1 on 2018-04-21 11:37

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_auto_20180420_1326'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=10), size=None),
        ),
    ]
