# Generated by Django 2.0.1 on 2018-04-19 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_auto_20180404_1229'),
        ('core', '0065_auto_20180419_0533'),
        ('core', '0060_auto_20180406_1132'),
    ]

    operations = [
    ]
