# Generated by Django 2.0.1 on 2018-04-21 16:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_auto_20180421_1514'),
        ('core', '0065_auto_20180419_0533'),
    ]

    operations = [
    ]
