# Generated by Django 2.0.4 on 2018-04-23 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_merge_20180419_1240'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='charge',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='djstripe.Charge'),
        ),
    ]
