# Generated by Django 2.0.1 on 2018-04-26 22:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_auto_20180421_1404'),
        ('core', '0067_auto_20180424_1236'),
    ]

    operations = [
    ]
