# Generated by Django 2.0.1 on 2018-04-26 22:17
import uuid

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_merge_20180426_2214'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(max_length=255, null=True)
        ),
    ]
