# Generated by Django 2.0.1 on 2018-04-26 22:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_add_guessed_supplier_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(max_length=255, unique=True, null=False),
        ),
    ]
