# Generated by Django 2.0.1 on 2018-04-26 23:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_auto_20180426_2227'),
        ('core', '0067_djstripe'),
    ]

    operations = [
    ]
