# Generated by Django 2.0.1 on 2018-04-27 14:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075b_order_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='core.Video'),
        ),
    ]
