# Generated by Django 2.0.1 on 2018-04-27 14:20
from django.db import migrations, models
import django.db.models.deletion


def _create_dummy_user(apps, schema_editor):
    User = apps.get_model('core', 'User')
    if not User.objects.filter(email='placeholder-migrations@dummy.user.no').exists():
        User.objects.create(email='placeholder-migrations@dummy.user.no',
                            username='migrations@dummy.user.no', is_active=False)

    return User.objects.filter(email='placeholder-migrations@dummy.user.no').first()


def _create_dummy_video(apps, schema_editor):
    Video = apps.get_model('core', 'Video')
    Order = apps.get_model('core', 'Order')

    # Only create dummy video if needed (helps keeping the test and possibly the production db clean)
    if Order.objects.filter(video__isnull=True).exists():
        if not Video.objects.filter(title='Dummy Migrations Placeholder Video').exists():
            dummy_owner = _create_dummy_user(apps, schema_editor)
            Video.objects.create(title='Dummy Migrations Placeholder Video', owner=dummy_owner, videofile='dummy.file')

        # Point any Orders without video to the dummy video
        dummy_video = Video.objects.filter(title='Dummy Migrations Placeholder Video').first()
        Order.objects.filter(video__isnull=True).update(video=dummy_video)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075a_order_video'),
    ]

    operations = [
        migrations.RunPython(code=_create_dummy_video, reverse_code=migrations.RunPython.noop)
    ]
