# Generated by Django 2.0.1 on 2018-04-28 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0075c_order_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='size',
            field=models.CharField(max_length=30),
        ),
    ]
