# Generated by Django 2.0.1 on 2018-04-29 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0076_auto_20180428_1202'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='commission_earned',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
    ]
