# Generated by Django 2.0.1 on 2018-03-19 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_taskrun'),
    ]

    operations = [
        migrations.RenameField(
            model_name='follow',
            old_name='to_user',
            new_name='follower'
        ),
        migrations.RenameField(
            model_name='follow',
            old_name='from_user',
            new_name='followed'
        )
    ]
