# Generated by Django 2.0.1 on 2018-05-11 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_taskrun'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='disabled',
            field=models.BooleanField(default=False, verbose_name='disabled'),
        ),
    ]
