# Generated by Django 2.0.1 on 2018-05-08 20:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0078_taskrun'),
    ]

    operations = [
        migrations.CreateModel(
            name='DefaultFollowRecommendation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DefaultFollowRecommendationRank',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.PositiveIntegerField(default=0)),
                ('rec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.DefaultFollowRecommendation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='follow_rank_users', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('rank',),
            },
        ),
        migrations.AddField(
            model_name='defaultfollowrecommendation',
            name='users',
            field=models.ManyToManyField(related_name='_defaultfollowrecommendation_users_+', through='core.DefaultFollowRecommendationRank', to=settings.AUTH_USER_MODEL),
        ),
    ]
