# Generated by Django 2.0.1 on 2018-05-18 00:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0079_user_disabled'),
        ('core', '0079_auto_20180508_2028'),
    ]

    operations = [
    ]
