# Generated by Django 2.0.1 on 2018-05-14 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0081_dedup_trending'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='trendinghashtag',
            unique_together={('hashtag', 'trending')},
        ),
        migrations.AlterUniqueTogether(
            name='trendingprofile',
            unique_together={('user', 'trending')},
        ),
    ]
