# Generated by Django 2.0.1 on 2018-05-18 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0082_auto_20180514_1432'),
        ('core', '0080_merge_20180518_0059'),
    ]

    operations = [
    ]
