# Generated by Django 2.0.1 on 2018-05-23 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0083_merge_20180518_0126'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='policy_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='privacy_policy_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='returns_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='supplier',
            name='returns_method',
            field=models.PositiveIntegerField(choices=[(0, 'N/A'), (1, 'CollectPlus'), (2, 'See Website')], default=0),
        ),
        migrations.AddField(
            model_name='supplier',
            name='returns_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=9),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shipping_method',
            field=models.PositiveIntegerField(choices=[(0, 'Standard Delivery UK & NI YODEL'), (1, 'UK Standard Delivery'), (2, 'Standard Shipping'), (3, 'Parcelforce')], default=1),
        ),
        migrations.AddField(
            model_name='supplier',
            name='terms_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True),
        ),
    ]
