# Generated by Django 2.0.1 on 2018-05-23 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0084_auto_20180523_1743'),
    ]

    operations = [
        migrations.AddField(
            model_name='supplier',
            name='return_period',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='shipping_time',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
