# Generated by Django 2.0.1 on 2018-06-10 15:13

from django.db import migrations, models
import django.db.models.deletion
import heartface.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0085_auto_20180523_1753'),
    ]

    operations = [
        migrations.CreateModel(
            name='Marketplace',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace_id', models.CharField(max_length=255, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('logo', models.ImageField(upload_to=heartface.apps.core.models.UploadDir('marketplace_logo'))),
                ('search_url_template', models.CharField(max_length=500, null=True)),
                ('affil_url_template', models.CharField(max_length=500, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MarketplaceURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link', models.URLField(max_length=500, unique=True)),
                ('marketplace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_urls', to='core.Marketplace')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='marketplace_urls', to='core.Product')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='marketplaceurl',
            unique_together={('marketplace', 'product')},
        ),
    ]
