# Generated by Django 2.0.1 on 2018-06-06 17:27

from django.db import migrations
from django.conf import settings
from django.db import IntegrityError


def _remove_default_marketplaces(apps, schema_editor):
    Marketplace = apps.get_model('core', 'Marketplace')
    Marketplace.objects.all().delete()

def _create_default_marketplaces(apps, schema_editor):
    Marketplace = apps.get_model('core', 'Marketplace')
    for mconf in settings.MARKETPLACES:
        try:
            Marketplace.objects.create(name=mconf['name'],
                                       marketplace_id=mconf['marketplace_id'],
                                       logo=mconf['logo'],
                                       search_url_template=mconf['search_url_template'],
                                       affil_url_template=mconf['affil_url_template']
                                       )
        except IntegrityError:
            continue


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0086_auto_20180610_1513'),
    ]

    operations = [
        migrations.RunPython(code=_create_default_marketplaces, reverse_code=_remove_default_marketplaces)
    ]
