# Generated by Django 2.0.1 on 2018-06-10 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0087_create_marketplaces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplaceurl',
            name='link',
            field=models.URLField(max_length=500),
        ),
    ]
