# Generated by Django 2.0.1 on 2018-06-06 17:27
from urllib.parse import quote

from django.db import migrations
from heartface.apps.core.signals import create_marketplace_urls


def _create_urls(apps, schema_editor):
    MarketplaceURL = apps.get_model('core', 'MarketplaceURL')
    Marketplace = apps.get_model('core', 'Marketplace')
    Product = apps.get_model('core', 'Product')

    for product in Product.objects.all():
        for marketplace in Marketplace.objects.exclude(search_url_template__isnull=True):
            link = marketplace.search_url_template % quote(product.name)
            if marketplace.affil_url_template:
                link = marketplace.affil_url_template % link
            MarketplaceURL.objects.get_or_create(marketplace=marketplace, product=product, link=link)


def _remove_dup_urls(apps, schema_editor):
    MarketplaceURL = apps.get_model('core', 'MarketplaceURL')
    for link in MarketplaceURL.objects.values_list('link', flat=True).distinct():
        MarketplaceURL.objects.filter(pk__in=MarketplaceURL.objects.filter(link=link).values_list('id', flat=True)[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0088_auto_20180610_1640'),
    ]

    operations = [
        migrations.RunPython(code=_create_urls, reverse_code=_remove_dup_urls)
    ]
