# Generated by Django 2.0.1 on 2018-06-06 17:27

from django.db import migrations
from django.db.models import Count


def _sync_follow_count(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for user in User.objects.all().annotate(cnt=Count('followers')).values('pk', 'cnt'):
        User.objects.filter(pk=user['pk']).update(follower_count=user['cnt'])


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_user_follow_count'),
    ]

    operations = [
        migrations.RunPython(code=_sync_follow_count, reverse_code=migrations.RunPython.noop)
    ]
