# Generated by Django 2.0.1 on 2018-06-19 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0090_auto_20180616_0040'),
        ('core', '0091_sync_follow_count'),
    ]

    operations = [
    ]
