# Generated by Django 2.0.1 on 2018-06-20 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_merge_20180619_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='affiliate_code',
        ),
    ]
