# Generated by Django 2.0.1 on 2018-06-19 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0092_merge_20180619_0044'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='policy_url',
        ),
        migrations.AlterField(
            model_name='supplier',
            name='privacy_policy_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True, verbose_name='Privacy policy'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='returns_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True, verbose_name='Returns'),
        ),
        migrations.AlterField(
            model_name='supplier',
            name='terms_url',
            field=models.URLField(blank=True, max_length=500, null=True, unique=True, verbose_name='T&Cs'),
        ),
    ]
