# Generated by Django 2.0.1 on 2018-06-21 00:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0093_remove_supplier_affiliate_code'),
        ('core', '0093_auto_20180619_1727'),
        ('core', '0094_auto_20180620_1056'),
    ]

    operations = [
    ]
