# Generated by Django 2.0.1 on 2018-06-27 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0095_merge_20180627_0949'),
        ('core', '0095_merge_20180621_0024'),
    ]

    operations = [
    ]
