# Generated by Django 2.0.1 on 2018-06-06 17:27
import re
from django.db import migrations


def _sync_vid_tags(apps, schema_editor):
    Video = apps.get_model('core', 'Video')
    Hashtag = apps.get_model('core', 'Hashtag')
    for v in Video.objects.all():
        hashtag_re = re.compile("(?:^|\s)[＃#]{1}(\w+)", re.UNICODE)
        tag_names = hashtag_re.findall(v.title)
        for tag_name in tag_names:
            if not v.hashtags.filter(name=tag_name).exists():
                tag_obj, created = Hashtag.objects.get_or_create(name=tag_name)
                v.hashtags.add(tag_obj)

        # Remove stale tags (no longer in title)
        for old_tag in v.hashtags.exclude(name__in=tag_names):
            v.hashtags.remove(old_tag)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0096_merge_20180627_0954'),
    ]

    operations = [
        migrations.RunPython(code=_sync_vid_tags, reverse_code=migrations.RunPython.noop)
    ]
