# Generated by Django 2.0.1 on 2018-07-04 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0098_auto_20180703_1845'),
        ('core', '0097_sync_vid_tags'),
    ]

    operations = [
    ]
