# Generated by Django 2.0.1 on 2018-07-05 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0099_merge_20180704_1816'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomepageContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('profiles', models.ManyToManyField(related_name='_homepagecontent_profiles_+', to=settings.AUTH_USER_MODEL)),
                ('videos', models.ManyToManyField(related_name='_homepagecontent_videos_+', to='core.Video')),
            ],
        ),
    ]
