# Generated by Django 2.0.1 on 2018-08-06 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0105_auto_20180731_1736'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='type',
            field=models.IntegerField(choices=[(0, 'New Follower'), (1, 'New Like'), (2, 'New Comment')]),
        ),
    ]
