# Generated by Django 2.0.1 on 2018-08-28 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0107_video_description'),
        ('core', '0107_auto_20180827_1053'),
    ]

    operations = [
    ]
