# Generated by Django 2.0.1 on 2018-09-01 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0109_remove_old_prods'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='colorway',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='product',
            name='release_date',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='stockx_id',
            field=models.CharField(default=None, max_length=100, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='style_code',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
