# Generated by Django 2.0.1 on 2018-09-01 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0111_reverse_pop_supplier_ids'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='supplier_id',
        ),
    ]
