# Generated by Django 2.0.1 on 2018-09-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0110_auto_20180901_1315'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplier',
            name='supplier_id',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
