# Generated by Django 2.0.1 on 2018-09-02 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0112_auto_20180901_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.IntegerField(choices=[(0, 'queued'), (1, 'processed')], default=0),
        ),
    ]
