# Generated by Django 2.0.1 on 2018-09-02 15:16

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0114_reverse_set_price_sizes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='supplierproduct',
            name='price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=9, null=True),
        ),
        migrations.AlterField(
            model_name='supplierproduct',
            name='sizes',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=30), blank=True, null=True, size=None),
        ),
    ]
