# Generated by Django 2.0.1 on 2018-09-07 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
from heartface.libs.utils import _dedup


def _dedup_reports(apps, schema_editor):
    ReportedVideo = apps.get_model('core', 'ReportedVideo')
    ReportedVideo.objects.filter(reporting_user=None).delete()
    _dedup(apps.get_model('core', 'ReportedVideo'), ['reporting_user', 'video'], '-created')


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0115_auto_20180902_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reportedvideo',
            name='reporting_user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='reportedvideo',
            unique_together=set(),
        ),
        migrations.RunPython(code=migrations.RunPython.noop, reverse_code=_dedup_reports),
    ]
