# Generated by Django 2.0.1 on 2018-09-25 17:37

from django.db import migrations, models
import django.utils.timezone
import heartface.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0117_supplierproduct_last_scraped'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='updated',
            field=models.DateTimeField(auto_now=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='primary_picture',
            field=models.ImageField(blank=True, null=True, upload_to=heartface.apps.core.models.UploadDir('product_images')),
        ),
        migrations.AlterField(
            model_name='product',
            name='stockx_id',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
