# Generated by Django 2.0.1 on 2018-09-29 20:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0119_auto_20180926_1958'),
    ]

    operations = [
        migrations.CreateModel(
            name='GlacierFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.BigIntegerField()),
                ('archive_id', models.CharField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('video', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='core.Video')),
            ],
        ),
    ]
