# Generated by Django 2.0.1 on 2018-10-10 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0120_glacierfile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='search_url_template',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
