# Generated by Django 2.0.1 on 2018-10-10 18:03

from django.db import migrations, models
import heartface.apps.core.models
import heartface.apps.core.storages


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_auto_20181010_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='primary_picture',
            field=models.ImageField(blank=True, null=True, storage=heartface.apps.core.storages.BunnyCDNStorage(), upload_to=heartface.apps.core.models.UploadDir('')),
        ),
    ]
