# Generated by Django 2.0.1 on 2018-10-10 17:29

from django.db import migrations, models
import heartface.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0121_auto_20181010_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='marketplace',
            name='affil_url_template',
            field=models.CharField(blank=True, default='', max_length=500),
            preserve_default=False,
        ),
    ]
