# Generated by Django 2.0.1 on 2018-10-15 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0122_auto_20181010_1803'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='release_date',
            field=models.DateField(blank=True, default=None, null=True),
        ),
    ]
