# Generated by Django 2.0.1 on 2018-10-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0123_auto_20181015_1307'),
    ]

    operations = [
        migrations.CreateModel(
            name='Proxy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.GenericIPAddressField()),
                ('port', models.PositiveIntegerField(default=443)),
                ('username', models.CharField(blank=True, max_length=30, verbose_name='Username')),
                ('password', models.CharField(blank=True, max_length=30, verbose_name='Password')),
                ('fail_count', models.IntegerField(db_index=True, default=0)),
            ],
            options={
                'verbose_name_plural': 'Proxies',
            },
        ),
        migrations.AlterUniqueTogether(
            name='proxy',
            unique_together={('ip_address', 'port')},
        ),
    ]
