# Generated by Django 2.0.1 on 2018-11-05 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0125_video_cdn_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAnalytic',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('core.video',),
        ),
        migrations.AddField(
            model_name='video',
            name='video_length',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]


