# Generated by Django 2.0.1 on 2018-11-15 11:48

from django.db import migrations
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0129_auto_20181114_1425'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='country',
            field=django_countries.fields.CountryField(blank=True, default='GB', max_length=2),
        ),
    ]
