# Generated by Django 2.0.1 on 2018-11-21 09:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import heartface.apps.core.models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0131_supplier_country'),
    ]

    operations = [
        migrations.CreateModel(
            name='MissingProduct',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('color', models.CharField(max_length=200)),
                ('style_code', models.CharField(blank=True, max_length=50)),
                ('notes', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to=heartface.apps.core.models.UploadDir('missing_products'))),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('handled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='handled_by', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Video')),
            ],
        ),
    ]
