# Generated by Django 2.0.1 on 2018-12-20 15:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0132_missingproduct'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoCDNStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('status', models.CharField(max_length=20)),
                ('description', models.TextField(null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cdn_status', to='core.Video')),
            ],
        ),
        migrations.AddIndex(
            model_name='videocdnstatus',
            index=models.Index(fields=['video'], name='core_videoc_video_i_d713e6_idx'),
        ),
    ]
