# Generated by Django 2.0.1 on 2018-12-27 15:21

from django.db import migrations, models
from datetime import date


def calculate_fake_birthday(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for user in User.objects.all():
        if user.age:
            user.birthday = date(2018 - user.age, 1, 1)
            user.save()


def calculate_user_age(apps, schema_editor):
    User = apps.get_model('core', 'User')
    for user in User.objects.all():
        if user.birthday:
            user.age = 2018 - user.birthday.year
            user.save()


class Migration(migrations.Migration):
    dependencies = [
        ('core', '0132_missingproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='birthday',
            field=models.DateField(null=True, blank=True),
            preserve_default=False,
        ),
        migrations.RunPython(code=calculate_fake_birthday, reverse_code=calculate_user_age),
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
    ]
