# Generated by Django 2.0.1 on 2019-01-06 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0133_auto_20181220_1556'),
        ('core', '0133_move_cron_tasks_to_db'),
    ]

    operations = [
    ]
