# Generated by Django 2.0.1 on 2019-01-07 18:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0134_merge_20190106_1723'),
        ('core', '0133_auto_20181227_1521'),
    ]

    operations = [
    ]
